class TextRenderer extends Renderer{
  constructor(char, alpha = 1.0){
    super(new Vec2(), new Vec2(1,1), false, alpha, ['UI']);
    this.isText = true;
    this.GetTileFromASCII(char);
  }

  GetTileFromASCII(char){
    const minChar = 33;
    const maxChar = 176;
    const tilesPerRow = 12;
    const tilesPerColumn = 12;

    let code = maxChar;
    if(CharToAscii.has(char)){
      code = CharToAscii.get(char);
    }

    Log("code: "+code);
    this.tile.x = code % tilesPerRow;
    this.tile.y =tilesPerColumn- (Math.floor(code/tilesPerRow)+1);
    Log(this.tile.toString('tile: '));
  }
}

var CharToAscii = new Map();
CharToAscii.set('!', 0);
CharToAscii.set('"', 1);
CharToAscii.set('#', 2);
CharToAscii.set('$', 3);
CharToAscii.set('%', 4);
CharToAscii.set('&', 5);
CharToAscii.set('`', 6);
CharToAscii.set('(', 7);
CharToAscii.set(')', 8);
CharToAscii.set('*', 9);
CharToAscii.set('+', 10);
CharToAscii.set(',', 11);
CharToAscii.set('-', 12);
CharToAscii.set('.', 13);
CharToAscii.set('/', 14);
CharToAscii.set('0', 15);
CharToAscii.set('1', 16);
CharToAscii.set('2', 17);
CharToAscii.set('3', 18);
CharToAscii.set('4', 19);
CharToAscii.set('5', 20);
CharToAscii.set('6', 21);
CharToAscii.set('7', 22);
CharToAscii.set('8', 23);
CharToAscii.set('9', 24);
CharToAscii.set(':', 25);
CharToAscii.set(';', 26);
CharToAscii.set('<', 27);
CharToAscii.set('=', 28);
CharToAscii.set('>', 29);
CharToAscii.set('?', 30);
CharToAscii.set('@', 31);
CharToAscii.set('A', 32);
CharToAscii.set('B', 33);
CharToAscii.set('C', 34);
CharToAscii.set('D', 35);
CharToAscii.set('E', 36);
CharToAscii.set('F', 37);
CharToAscii.set('G', 38);
CharToAscii.set('H', 39);
CharToAscii.set('I', 40);
CharToAscii.set('J', 41);
CharToAscii.set('K', 42);
CharToAscii.set('L', 43);
CharToAscii.set('M', 44);
CharToAscii.set('N', 45);
CharToAscii.set('O', 46);
CharToAscii.set('P', 47);
CharToAscii.set('Q', 48);
CharToAscii.set('R', 49);
CharToAscii.set('S', 50);
CharToAscii.set('T', 51);
CharToAscii.set('U', 52);
CharToAscii.set('V', 53);
CharToAscii.set('W', 54);
CharToAscii.set('X', 55);
CharToAscii.set('Y', 56);
CharToAscii.set('Z', 57);
CharToAscii.set('[', 58);
//CharToAscii.set("undefined", 59);
CharToAscii.set(']', 60);
CharToAscii.set('^', 61);
CharToAscii.set('_', 62);
CharToAscii.set('`', 63);
CharToAscii.set('a', 64);
CharToAscii.set('b', 65);
CharToAscii.set('c', 66);
CharToAscii.set('d', 67);
CharToAscii.set('e', 68);
CharToAscii.set('f', 69);
CharToAscii.set('g', 70);
CharToAscii.set('h', 71);
CharToAscii.set('i', 72);
CharToAscii.set('j', 73);
CharToAscii.set('k', 74);
CharToAscii.set('l', 75);
CharToAscii.set('m', 76);
CharToAscii.set('n', 77);
CharToAscii.set('o', 78);
CharToAscii.set('p', 79);
CharToAscii.set('q', 80);
CharToAscii.set('r', 81);
CharToAscii.set('s', 82);
CharToAscii.set('t', 83);
CharToAscii.set('u', 84);
CharToAscii.set('v', 85);
CharToAscii.set('w', 86);
CharToAscii.set('x', 87);
CharToAscii.set('y', 88);
CharToAscii.set('z', 89);
CharToAscii.set('{', 90);
CharToAscii.set('|', 91);
CharToAscii.set('}', 92);
CharToAscii.set('~', 93);
CharToAscii.set('Ç', 94);
CharToAscii.set('ü', 95);
CharToAscii.set('é', 96);
CharToAscii.set('â', 97);
CharToAscii.set('ä', 98);
CharToAscii.set('à', 99);
CharToAscii.set('0', 100);
CharToAscii.set('ç', 101);
CharToAscii.set('ê', 102);
CharToAscii.set('ë', 103);
CharToAscii.set('è', 104);
CharToAscii.set('ï', 105);
CharToAscii.set('î', 106);
CharToAscii.set('ì', 107);
CharToAscii.set('Ä', 108);
CharToAscii.set('A', 109);
CharToAscii.set('É', 110);
CharToAscii.set('0', 111);
CharToAscii.set('0', 112);
CharToAscii.set('ô', 113);
CharToAscii.set('ò', 114);
CharToAscii.set('û', 115);
CharToAscii.set('ù', 116);
CharToAscii.set('ý', 117);
CharToAscii.set('Ö', 118);
CharToAscii.set('Ü', 119);
CharToAscii.set('Á', 120);
CharToAscii.set('Í', 121);
CharToAscii.set('Ó', 122);
CharToAscii.set('Ú', 123);
CharToAscii.set('0', 124);
CharToAscii.set('á', 125);
CharToAscii.set('í', 126);
CharToAscii.set('ó', 127);
CharToAscii.set('ú', 128);
CharToAscii.set('ñ', 129);
CharToAscii.set('Ñ', 130);
CharToAscii.set('ª', 131);
CharToAscii.set('º', 132);
CharToAscii.set('¿', 133);
CharToAscii.set('0', 134);
CharToAscii.set('¬', 135);
CharToAscii.set('0', 136);
CharToAscii.set('0', 137);
CharToAscii.set('¡', 138);
CharToAscii.set('0', 139);
CharToAscii.set('0', 140);
CharToAscii.set('0', 141);
CharToAscii.set('0', 142);
CharToAscii.set(' ', 143);
